
services:

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: defaultpassword
      MYSQL_DATABASE: gda
    networks:
      - GDA
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  openlist:
    image: openlistteam/openlist:latest
    restart: always
    container_name: openlist
    user: '0:0'
    ports:
      - 5244:5244
    networks:
      - GDA
    environment:
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - GDA_DATA:/gda
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  gda:
    image: ghcr.io/xiaoyaohanyue/gda:latest
    restart: always
    container_name: gda
    networks:
      - GDA
    volumes:
      - GDA_DATA:/gda
      - ./config:/app/config
      - ./logs:/app/logs
      - ./sessions:/app/sessions
    depends_on:
      db:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  GDA:

volumes:
  GDA_DATA: