
services:

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: defaultpassword
      MYSQL_DATABASE: gda
    networks:
      - GDA
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  alist:
    image: xhofe/alist:beta
    restart: always
    container_name: alist
    ports:
      - 5244:5244
    networks:
      - GDA
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    volumes:
      - GDA_DATA:/gda
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  
  gda:
    image: ghcr.io/xiaoyaohanyue/gda:latest
    restart: always
    container_name: gda
    networks:
      - GDA
    volumes:
      - GDA_DATA:/gda
      - ./config:/app/config
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  GDA:
    external: true

volumes:
  GDA_DATA:
    external: true