"""初始化

Revision ID: 6ace8bf34422
Revises: 
Create Date: 2025-10-27 16:35:11.775871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ace8bf34422'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupitem',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='会话ID'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groupitem'))
    )
    op.create_index(op.f('ix_groupitem_chat_id'), 'groupitem', ['chat_id'], unique=True)
    op.create_table('listitem',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='名称'),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='版本号'),
    sa.Column('new_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='最新版本号'),
    sa.Column('repository', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='仓库地址'),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='存放子路径'),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='状态'),
    sa.Column('links', mysql.JSON(), nullable=True, comment='下载链接'),
    sa.Column('start_at', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_at', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listitem')),
    sa.UniqueConstraint('repository', name=op.f('uq_listitem_repository'))
    )
    op.create_index(op.f('ix_listitem_name'), 'listitem', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listitem_name'), table_name='listitem')
    op.drop_table('listitem')
    op.drop_index(op.f('ix_groupitem_chat_id'), table_name='groupitem')
    op.drop_table('groupitem')
    # ### end Alembic commands ###
