"""新增存放路径字段

Revision ID: 8df6f30ab268
Revises: f39e99c2a906
Create Date: 2025-10-26 12:05:59.185197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8df6f30ab268'
down_revision: Union[str, Sequence[str], None] = 'f39e99c2a906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listitem', sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False, comment='存放子路径'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listitem', 'path')
    # ### end Alembic commands ###
