"""修改chat_id的存储类型

Revision ID: c2c9f1c7fd93
Revises: 6ace8bf34422
Create Date: 2025-10-27 18:36:41.594670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c2c9f1c7fd93'
down_revision: Union[str, Sequence[str], None] = '6ace8bf34422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groupitem', 'chat_id',
               existing_type=mysql.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_comment='会话ID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groupitem', 'chat_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=mysql.INTEGER(),
               existing_comment='会话ID',
               existing_nullable=False)
    # ### end Alembic commands ###
